# name: Cypress Tests and Deployment

# on: [push]

# jobs:
#   cypress-run:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           build: yarn run build
#           start: yarn start
#           record: true
#     # Define an output that the deploy job can use
#     outputs:
#       cypress-status: ${{ job.status }}

#   deploy:
#     needs: cypress-run
#     # Only run if the cypress-run job has a status of success
#     if: steps.cypress-run.outputs.cypress-status == 'success'
#     runs-on: windows-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Install dependencies
#         run: npm ci
#       - name: Build application
#         run: npm run build
#       - name: Deploy application
#         run: npm run deploy
